### ISSUE TITLE
11/10 Discussion

### ISSUE THREAD

**Issue by euugenechou** [lkuper/CSE232-2021-09#11]
List of scribes (may be missing some if manager hasn't updated the rolesheet):

- @15siegela 
- @AnirudhPotlapally
- @brianwzhao
- @aakash-mishra
- @Aditya-1996
- @jabowen
- @nliittsc
- @pan-jessica
- @tanujtinish

**Comment by pan-jessica** [comment]
Thanks for creating the issue!

Created the collab doc:
https://docs.google.com/document/d/1V-lFquZ7FzqCbUrQ-sVDAG07IaLT97GhLVMvGKBzn24/edit?usp=sharing

**Comment by lkuper** [comment]
Thanks for getting this going!

**Comment by aakash-mishra** [comment]
I've just added answers to questions 1 and 3. I am not too confident about the last part of answer 3 and it'd be great if someone could write a little bit more about exactly once message delivery.

**Comment by tanujtinish** [comment]
For question 3,

I have extended the explanation for exactly-once message delivery.
Also added 2 other possible models discussed in class.

**Comment by Aditya-1996** [comment]
Added the paper overview and added other points in Q1.
The rest of it seems fine. 

Anyone, feel free to check paper overview and make changes as necessary.

**Comment by pan-jessica** [comment]
I just finished writing up the summaries of all the questions & overview in the google doc. Feel free to make any necessary changes and if someone can look it over, that'd be great!

**Comment by 15siegela** [comment]
Just gave it a quick read through, looks great. Nice work everyone!
Thanks,
Alec Siegel

**Comment by Aditya-1996** [comment]
Looks like somebody had already committed changes to the wiki for summaries to discussion questions. I added the paper summary. Feel free to look it over and make changes

**Comment by lkuper** [comment]
Hey folks, thanks for the writeup. Some feedback:

> This is an ideal algorithm and is generally difficult to implement.

It's not that it's "generally difficult" to implement, it's that it's impossible -- this is the whole point of the paper!

> A) Using timeouts- This adds synchrony to the system (and thus relaxes the asynchronous model specification). Example: Paxos uses timeouts.

I would phrase this differently.  I wouldn't say that using timeouts turns an asynchronous system into a synchronous system, which is what it kind of sounds like you're saying here.  If that's what using timeouts did, then we could easily have a totally correct consensus protocol, but of course, Paxos isn't that.  I'd say that what we do instead is just choose some timeout length beyond which we're not willing to wait for conditions to be met that we need for Paxos to progress (e.g., for a majority of acceptors to respond to a request), and instead we just start over in the hope that in the next run, it'll work better.
