### ISSUE TITLE
11/29 Discussion -- Amazon's Dynamo

### ISSUE THREAD

**Issue by nileshnegi** [lkuper/CSE232-2021-09#13]
@tanujtinish 
@reeselevine 
@plredmond 
@nikam 
@jabowen 
@Aditya-1996 
@ekalvan 
@Donnie-Stewart 
@das-17 
@ananyadas2607

**Comment by plredmond** [comment]
I added some text to the wiki page. Please adjust or correct it, or add your own text.

Wiki page: https://github.com/lkuper/CSE232-2021-09/wiki/11-29-Dynamo-Amazons-Highly-Available-Key-value-Store

```diff
  ### Q1

+ Dynamo prioritizes availability, whereas Chubby prioritizes consistency. Dynamo's choice to accept all writes and only surface conflicts to clients at read-time demonstrates that it sacrifices C(onsistency) from CAP in favor of A(valability).
```
This doesn't really say anything about how Chubby's design or implementation contribute to its prioritization of consistency.
```diff

  ### Q2

+ An advantage of a decentralized failure detection model is that every node can gain some perspective on which nodes are currently available. The ability to have some view of other nodes' availability is not hampered by the scale of the cluster or the outage of some particular node. However, a disadvantage of this approach is that each node develops a separate perspective of other nodes' availability. Assuming that nodes eventually arrive at the same perspective, there's still significant time periods where the nodes' do not agree about which nodes are available. In case of a network partition, the nodes on one side of the partition would conclude that the nodes on the other side are down, but nodes on both sides are wrong in this case.

+ An advantage of a centralized failure detection model is that most nodes will agree about which other nodes are up or down, because most nodes will have an up-to-date perspective provided by the centralized detector. Disadvantages of this approach include: The detector is a single point of failure, for a large scale cluster the detector might not fail but it could become slow and inaccurate, and that in case of a network partition the detector will necessarily be on one side of the partition. On the detector side of the partition, nodes will see the other side as down. On the other side of the partition, it's not clear what nodes will see; perhaps they'll just use the stale view, or perhaps they fall back to a decentralized approach.
```

```diff
  ### Q3

+ An SLA measured at the 99.9th percentile means that 99.9% of some category of things will fall within SLA. So if the category is "request response time" and the SLA is "less than 50ms" then it meas that 99.9% of requests will have a response in less than 50ms.

+ An alternative might be measure the SLA in terms of the average, or the maximum. However, an SLA for "average response time of 50ms" could admit a very noisy distribution of response times (many taking 1ms, and some taking seconds). Likewise, an SLA for "maximum response time of 50ms" is too inflexible and would frequently be broken by unpredictable network spikes, occasional OS swapping, etc.
```

**Comment by plredmond** [comment]
Please set your availability for the next week so that we can suggest meeting times to complete the wiki page.

https://www.when2meet.com/?13801449-uqrQR

**Comment by plredmond** [comment]
Only 3 people have filled out their availability. Currently it seem **Saturday & Sunday between 1pm and 4:30pm are the best times to meet.**

**Comment by ekalvan** [comment]
can we just do a google doc

**Comment by Aditya-1996** [comment]
Created a collab doc and added my comments in a different colour:

https://docs.google.com/document/d/1Ee-zdU3HjSnFNjWMdXqHIXuxWA3lYAgc/edit?usp=sharing&ouid=106371757333183179092&rtpof=true&sd=true

Feel free to add your comments/make edits as necessary.

I'm open to meeting too if required, at those times.

**Comment by lkuper** [comment]
Hey, folks, thanks for the writeup.

This all looks very good, except that the paper overview is missing. :( Maybe you forgot to do that part?

If i were to add anything to Q2, I might point out that it seems like a great example of a safety/liveness tradeoff.  Decentralized failure detection seems to prioritize a liveness property ("participants can eventually get information about who is up or down"): different participants may have differing views of who is up, but at least they can get some sort of information, even if it's not quite right.  Centralized failure detection seems to prioritize a safety property ("everyone who has information about who is up or down has the *same* information").

For Q4, I think the Git example is better than the banking example.  People do use banking examples a lot in this context in distributed systems papers, but it doesn't actually match my experience interacting with banks!  In fact, my bank might show me something like "here's your balance, but here's what your balance *will* be once these pending transactions happen", which to me is analogous to Dynamo showing me multiple versions of a value I read.  That sounds like pushing the complexity to the read side.  So banks may be more "always writeable" than we realize!  :)  Banks also do things like reorder transactions after the fact, which sounds more like "always writeable" to me, too: accept the transaction whenever it shows up and then sort out the details later.
