### ISSUE TITLE
10/04  Discussion

### ISSUE THREAD

**Issue by sukeswan** [lkuper/CSE232-2021-09#2]
@lkuper @ananyadas2607 @aakash-mishra @Smruthi-Pobbathi @spacely @Eric-Vin @AnirudhPotlapally @Koda98 @philtcb  @SiegeEngine1

**Comment by nikam** [comment]
Hey, can you please add @Eric-Vin as one of the scribes for the 10/04 Discussion? I just updated the excel sheet :)

**Comment by tanujtinish** [comment]
@AnirudhPotlapally Hey scribe, an issue has been created.

**Comment by Eric-Vin** [comment]
Hey everyone, should we coordinate our edits on the Zulip scribes channel? I'll add my notes to the wiki in the meantime.

**Comment by SiegeEngine1** [comment]
Should we all just meet up after class today?
Also, I'm a scribe for 10/4 as well

**Comment by AnirudhPotlapally** [comment]
Me too. Where do I add the notes?

**Comment by lkuper** [comment]
@AnirudhPotlapally Y'all can use whatever tools you want to collaboratively edit your discussion summary, as long as it ends up here on the wiki.  (I'll just remind you that if you want to get a round of feedback from me before the deadline (which is quickly approaching), put your stuff on the wiki and tag me.)

**Comment by Eric-Vin** [comment]
Hey Everyone, I'm going to go ahead and consolidate our notes into answers. If another scribe could take a look and proofread when I'm done that would be great.

**Comment by spacely** [comment]
Will proof read when done

**Comment by Eric-Vin** [comment]
Thanks @spacely, I've just published the changes. Please let me know if you find any typos or want to change anything.

**Comment by spacely** [comment]
I proofread the existing doc and fixed the little typos.
I updated the paper overview section and would like someone to look
through that as well.

Saheed.

**Comment by aakash-mishra** [comment]
I'd be happy to proofread that (along with the overall doc)

**Comment by aakash-mishra** [comment]
Made minor typo corrections. Looks good to me.

**Comment by Smruthi-Pobbathi** [comment]
I read the doc. It looks good to me.

**Comment by byananya** [comment]
I read through the whole document and it looks good to me.

**Comment by AnirudhPotlapally** [comment]
I read it too. The doc looks good to me.

**Comment by Eric-Vin** [comment]
@lkuper Hi Professor Kuper, it looks like we're ready to submit a draft.

**Comment by lkuper** [comment]
Hey folks!  This looks pretty good.  I think you summarized the in-class discussion well.  My main feedback is that it seems there's some stuff left out of the paper overview; it doesn't mention any of the stuff from the "Ordering the Events Totally" section of the paper forward.

Nitpick:

> assigns a clock process to an ordered process

I'm not sure what this phrase means.

**Comment by Eric-Vin** [comment]
@lkuper I went ahead and expanded the paper overview section. Please let me know if there's anywhere else you feel needs a little more work!

**Comment by philtcb** [comment]
Sorry about the late reply! I read it too and it looks good to me!

**Comment by lkuper** [comment]
Thanks all!  Nice work.  It looks like you addressed the issues mentioned in my [previous comment](https://github.com/lkuper/CSE232-2021-09/issues/2#issuecomment-939622892).
