### ISSUE TITLE
10/08 Discussion

### ISSUE THREAD

**Issue by EIRNf** [lkuper/CSE232-2021-09#3]
Scribe list for this discussion! Please add anyone who is missing!
@brianwzhao 
@nileshnegi 
@rahula00 
@sukeswan 
@tanujtinish

**Comment by nikam** [comment]
@gshen42 Hello Scribe, adding you here :)

**Comment by nileshnegi** [comment]
Let's sync up after class today?

**Comment by sukeswan** [comment]
Hi. I just read this and missed the scribe meet-up after class today. Could someone fill me in? Thank you!

**Comment by nileshnegi** [comment]
We didn't meet up last time... How about we do this today? @brianwzhao @rahula00 @sukeswan @tanujtinish @gshen42

**Comment by sukeswan** [comment]
Hi Everyone! Made a google doc we can all edit. When we are done, I can add all the doc info to the git wiki. 

https://docs.google.com/document/d/1LVFSMla4z_O_OjvYeImcrnwurGNYCnOY3D6SnsAwJdY/edit?usp=sharing

**Comment by lkuper** [comment]
Just give me a heads up if you want me to give feedback on a draft before the deadline.

**Comment by gshen42** [comment]
> Hi Everyone! Made a google doc we can all edit. When we are done, I can add all the doc info to the git wiki.
> 
> https://docs.google.com/document/d/1LVFSMla4z_O_OjvYeImcrnwurGNYCnOY3D6SnsAwJdY/edit?usp=sharing

Me and some other scribes met up after the class and agreed on just editing the wiki directly.

I tweaked the answer to Q2 a little bit and wrote a paper overview based on my Canvas discussion, feel free to add/tweak these parts.

**Comment by nileshnegi** [comment]
> 
> 
> Just give me a heads up if you want me to give feedback on a draft before the deadline.

Prof. @lkuper, can you please review the wiki for 10/08?

**Comment by lkuper** [comment]
Hey folks!  Thanks for the discussion summary, and sorry I didn't have time to give feedback before the deadline.  Your answers to the first two questions look pretty good!  My feedback all has to do with the last question:

> It is a safe property.

This should say "safety property".  Also, if you're going to be tagging things as safety properties or liveness properties, causal consistency would also be a safety property.  Consistency models in general are described by safety properties; they rule out certain "bad" kinds of disagreement between replicas.  Causal consistency and strong consistency would both fall into this category, as would FIFO (aka PRAM) consistency and many more.

> Consistent system -- an abstract way of looking at consistency -- a system is consistent if it generates the same output for the same input and algorithm, in a 'reasonably similar' amount of time.

Not really sure where this is coming from.  Do you have a source?  If we ignore the "'reasonably similar' amount of time" part, it sounds to me like determinism.

> Consistency on the previous paper -- mutual exclusion/synchronization

Not sure what this is about.  Why is this "consistency"?

> Consistency in ACID properties denoted by character C -- It talks about consistency of shared data

This is kind of a circular definition.  If you're going to talk about consistency in the sense of the C in ACID, I recommend the excerpt from Kleppmann's book which I pointed to [on Zulip](https://ucsc-cse232.zulipchat.com/#narrow/stream/301155-general/topic/ACID.2C.20etc.2E).
