### ISSUE TITLE
10/13 Discussion

### ISSUE THREAD

**Issue by SiegeEngine1** [lkuper/CSE232-2021-09#4]
Scribe list for discussions on 10/13:
@AnirudhPotlapally 
@Donnie-Stewart 
@pan-jessica 
@reeselevine 
@xuyanwen2012 
@kevalnagda 
@NavikaG 
@nikam

**Comment by Eric-Vin** [comment]
Hi Everyone, I'm actually an ambassador not a scribe. I've fixed the discussion roles spreadsheet.

**Comment by lkuper** [comment]
How's it coming along?

**Comment by nikam** [comment]
Hey everyone, let's meet after the class?

**Comment by pan-jessica** [comment]
https://docs.google.com/document/d/1RvtRW47vjdK6ivJwVFw8uz28Iwyox0RNVjT8vsrkHMU/edit?usp=sharing

**Comment by nikam** [comment]
Thanks Jessica!

Wiki update:
Q1 is me
Q2 @Smruthi-Pobbathi 
Q3 is @AnirudhPotlapally 

Let's complete it by 12 Tonight!l ^_^

**Comment by nikam** [comment]
@lkuper Sorry for the late response. We are done with the [write-up](https://github.com/lkuper/CSE232-2021-09/wiki/10-13-Lightweight-Causal-and-Atomic-Group-Multicast). Would you like to have a look?

**Comment by lkuper** [comment]
Thanks, all -- I've taken a look.  Some comments:

> the paper proves several results related to fault tolerance and message stability

What were the proofs that had to do with stability?  (BTW, it's okay to only summarize the part of the paper that I actually asked you to read; you don't have to worry about the remaining sections.)

Your answers for Q1 and Q3 look OK.  For Q2, it looks like there are some misunderstandings.  The comparison isn't really between ABCAST and Lamport clocks.  It's between ABCAST and Lamport's proposed "state machine" approach to make every process execute the same sequence of commands in the same order, which is based on extending the happens-before partial order to a total order.

> Lamport method suggests choosing a process uniquely to break a tie.

The Lamport approach is to pick some arbitrary ordering of the processes to order concurrent events.  I don't know what you mean by "choosing a process uniquely".

> Lamport's clock can follow total ordering.

Not sure what this means, either.  Maybe what you meant to say is that the happens-before order can be extended to a total order.
