### ISSUE TITLE
10/27 Discussion

### ISSUE THREAD

**Issue by plredmond** [lkuper/CSE232-2021-09#7]
Here's the list of scribes for discussion on Oct 27th. Please edit this issue description to add yourself to the list if you were a scribe on this day.

* @plredmond
* @xuyanwen2012
* @EIRNf
* @pan-jessica
* @Smruthi-Pobbathi 
* @tanujtinish
* @aakash-mishra
* @15siegela
* @ananyadas2607 
* @xuyanwen2012

Here's a blank document we can use to collaboratively construct answers for today's discussion questions:

* https://docs.google.com/document/d/1g8CnosQ9mNo3FBhXG91HJYBg5p9mII1thd4R1f-pt-c/edit  
  (If folks decided last week that this approach didn't work, then just delete this link or comment below.)

Here's the wiki page we need to update with our combined discussion answers:

* https://github.com/lkuper/CSE232-2021-09/wiki/10-27-Knowledge-and-Common-Knowledge-in-a-Distributed-Environment

**Comment by aakash-mishra** [comment]
Should we meet after class today to discus the issue?

**Comment by plredmond** [comment]
Hi! Our discussion summary is due Wednesday (in two days), Nov 3.

When can you meet? Please indicate your availability here:
~~https://www.when2meet.com/?13492769-A16gc~~ (poll is outdated)

**Comment by plredmond** [comment]
Hi! Sending a followup message: We are scribes for Oct 27th discussion and we are responsible to produce a summary by Wednesday this week. What is your availability to meet **today or tomorrow**? ~~https://www.when2meet.com/?13492769-A16gc~~ (poll is outdated)

So far 3 people have filled the survey out, and it looks like Tuesday afternoon (today) is a good time to meet, perhaps. More people need to fill it out. :)

**Comment by plredmond** [comment]
So far only 5 people have responded, so it's hard to say what the best time to meet is. Could folks try to respond tonight (tuesday) and then we could possibly meet tomorrow (wednesday) and get it gone?

**Comment by aakash-mishra** [comment]
Hi guys, seeing as we have little time remaining before the deadline, I went ahead and updated the paper overview and answer to question 1. Could someone please write answers to question 2 and 3? (my notes are a mess!)
Also, if someone could proof-read whatever is on the page so far, that'd be awesome.

**Comment by pan-jessica** [comment]
I just completed/updated questions 2 and 3. Please let me know if I'm missing anything (or you can edit yourself) and if someone could proofread Q2 and Q3 too, that'd be great! 

@aakash-mishra I think it looks good!

**Comment by tanujtinish** [comment]
I just made minor updates in q2 and q1.
But besides that everything looks good to go.

**Comment by byananya** [comment]
I proofread the whole document. It looks good to me.

**Comment by Smruthi-Pobbathi** [comment]
I have updated the example of Q1 and proofread the document; looks good to go.

**Comment by lkuper** [comment]
Hi folks!  Thank you for the writeup.  Here's some feedback:

> it is impossible to agree on things

I would be more specific and say that it is impossible to reach common knowledge in this situation.

> because of the announcement, every child now knows that every other child also knows that there is at least one child with a muddy head.

Not only that, but now "there is at least one child with a muddy head" is actually common knowledge, meaning that every child knows that (... infinite repetitions of "every child knows that" ...) every child knows that there is at least one child with a muddy head.  People often confuse E^2 knowledge of a fact (everyone knows that everyone knows the fact) with common knowledge of the fact, but they are different things.

> Dual of 2 properties mean that one property can be expressed in terms of the other property.

The notion of duality is very general (and hard to explain -- I probably didn't explain it well in class).  I wouldn't use the word "property" here; I would say "concept" instead.  Also, it isn't just that one can be expressed in terms of the other but that *both* can be expressed in terms of the other (which I think is what you meant, but that wording might be more clear).
