### ISSUE TITLE
11/1 Discussion

### ISSUE THREAD

**Issue by AnirudhPotlapally** [lkuper/CSE232-2021-09#8]
Scribe list for discussions on 11/1:
@das-17 
@euugenechou 
@gshen42 
@Aditya-1996 
@NavikaG 
@pan-jessica 
@reeselevine 
@plredmond 
@sukeswan

**Comment by Aditya-1996** [comment]
Thank you Anirudh.

Created the collab doc:
https://docs.google.com/document/d/1Cb941OhPgHBx8IIPf6QqEWUDjoRvosl-n2q2iubMIzU/edit?usp=sharing

Everyone feel free to add your comments in diff colours, along the same lines as in [this](https://docs.google.com/document/d/1uYFFx2FzPpbiK1oUwW-13ZxMG60Z8ExXNZsoWg5x3ZM/edit?usp=sharing), and we'll collab on a final summary once we have all the contributions

**Comment by euugenechou** [comment]
Hi everyone,

I've summarized all the contributions placed in the Google doc thus far.
If there are any issues or anything missing, please address them sometime before 11:30pm.
I'll move everything to the wiki after then.

**Comment by Aditya-1996** [comment]
Excellent touch with the diagrams. I made some changes and fixed some typos and errors. Looks good otherwise.

**Comment by lkuper** [comment]
Thanks for the good writeup!  One very minor nitpick: my "ghost deadlock" example came from this book chapter, which Gärtner cites: https://www.cs.unibo.it/babaoglu/papers/pdf/global-states.pdf .  It is figure 4.2, and section 4.2 describes the concept of ghost deadlock.  It would be good if you cite the original source.  (You wouldn't have known this from class, but now you do.)

**Comment by euugenechou** [comment]
Thank you for the feedback! The citation has been added.
